DepartmentSite\DictionaryBundle\Entity\Dictionary:
    type: entity
    table: null
    repositoryClass: DepartmentSite\DictionaryBundle\Repository\DictionaryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 255
            unique: true
        title:
            type: string
            length: 255
            unique: true
        value:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
