department_site_menu_menu:
    resource: "@DepartmentSiteMenuBundle/Resources/config/routing/menu.yml"
    prefix:   /menu

department_site_menu_homepage:
    path:     /
    defaults: { _controller: DepartmentSiteMenuBundle:Default:index }
